### ISSUE TITLE
Registeration 

### ISSUE THREAD

**Issue by b15udi09er** [neuralpain/qbactivator#10]
Hello, i have the v19 version of QuickBooks but I can't complete the registration after putting the "99999930" code "step: 15", it will give me that QuickBooks was un-able to complete the activation, the quits. I have completed each and every step correctly. Please any help

**Comment by neuralpain** [comment]
Hi. Were you connected to the internet during installation?

Ref: https://github.com/neuralpain/qbactivator/issues/8#issuecomment-1402163041

**Comment by b15udi09er** [comment]
Hello, yes i was regarding the note before starting that i have to be
connected

**Comment by neuralpain** [comment]
Contact me on telegram: t.me/neuralpain

**Comment by neuralpain** [comment]
Issue resolved. User attempted to run individual files from the repository source rather than the release archive which resulted in malfunction of the script.
