### ISSUE TITLE
Quickbooks desktop activate

### ISSUE THREAD

**Issue by krishan1987** [neuralpain/qbactivator#16]
sir, 

Is there solution for quickbooks desktop activate?

**Comment by neuralpain** [comment]
Please use the beta release here and select option 3 for general activation: https://github.com/neuralpain/qbactivator/releases/

![image](https://github.com/neuralpain/qbactivator/assets/77242216/46a47cb1-6b31-4c26-ae62-f6a4978f0c7d)

**Comment by muhammad-adeel-77** [comment]
I think so there would be some activation for Quickbooks desktop as well
