### ISSUE TITLE
ectra user activation failed

### ISSUE THREAD

**Issue by clementkl** [neuralpain/qbactivator#17]
hello i tried to use the code for extra user code you gave 99999930?, but didint work, what do i do?

**Comment by neuralpain** [comment]
Hi. Was qbactivator running when you attempted to enter the [activation code](https://github.com/neuralpain/qbactivator/wiki/How-to-Use)? If you exit the activator prematurely, the activation may not be successful. Also ensure that you have [an internet connection](https://github.com/neuralpain/qbactivator#a-few-things-before-you-start) available for successful activation.

**Comment by clementkl** [comment]
hello,thnaks bro , it worked after running keeping the activator running

**Comment by neuralpain** [comment]
Well done. You're welcome.
