### ISSUE TITLE
online activation

### ISSUE THREAD

**Issue by clementkl** [neuralpain/qbactivator#18]
Ok so this is my first time on github so am still learning. so far it been interesting how solutions are being discussed and given. Am learning a lot. A quick one concerning the QuickBooks. Is it possible to get activation for the online version, a nulled one maybe?

thanks

**Comment by neuralpain** [comment]
Hello. Welcome to the community.

It's not possible to license a solution for the QuickBooks Online. As the software is fully online, it doesn't have a license number. You will have a Company ID instead.
