### ISSUE TITLE
Second License needed

### ISSUE THREAD

**Issue by cigarmantony** [neuralpain/qbactivator#19]
When running 2 stores, both cannot have the same license. I need to enter a different license for the second store.

**Comment by neuralpain** [comment]
Hello. I recently published [release v0.20.1](https://github.com/neuralpain/qbactivator/releases/latest) which allows allows you to choose whether you are doing a single/client install or you are installing a server workstation. Licenses have been provisioned for each.

![image](https://github.com/neuralpain/qbactivator/assets/77242216/18c43ac5-f146-4ca8-a21e-30e94105454e)

Please let me know if you encounter any more issues with the licensing.

**Comment by neuralpain** [comment]
Hi. Use the latest release [`v0.20.2`](https://github.com/neuralpain/qbactivator/releases/tag/v0.20.2) which supports multi-store licensing.
