### ISSUE TITLE
CANNOT REVERSE TRANSACTIONS

### ISSUE THREAD

**Issue by MONKE121** [neuralpain/qbactivator#27]
Hey my friend it's me from Telegram.

I receiving an error which due to discontinued of the Point Of Sale System.

Here is the link of people receiving the same issues: https://quickbooks.intuit.com/learn-support/en-us/other-questions/can-no-longer-reverse-a-transaction/00/1328642

Please fix it.

Thank you

![image](https://github.com/neuralpain/qbactivator/assets/112748093/8369fcdf-7e6d-4cc9-b542-a30ec4587b89)

**Comment by SESNut** [comment]
The last update where this issue doesnt exist is R8. If you update to R9 or above you get this error. Unfortunately if you upgrade your database will be marked with a later version and it will ask you to check for updates every time you login so its not actually possible to downgrade to an older version
