### ISSUE TITLE
Failed to Launch QB POS V19

### ISSUE THREAD

**Issue by MalikandMalik** [neuralpain/qbactivator#34]
Hello Sir,

I downloaded qb pos V19 follwed by installed on my computer successflly, however after configuration practice company it pops up with invalid product number. upon clicking OK it exit the programme with no further action.
please help

**Comment by neuralpain** [comment]
Which version of qbactivator did you use to activate QuickBooks POS v19?

**Comment by MalikandMalik** [comment]
> Which version of qbactivator did you use to activate QuickBooks POS v19?

Yes Sir, thats it - POSv19

**Comment by MalikandMalik** [comment]
> > Which version of qbactivator did you use to activate QuickBooks POS v19?
> 0.21.1

**Comment by MalikandMalik** [comment]
> Which version of qbactivator did you use to activate QuickBooks POS v19?

0.21.1

**Comment by MalikandMalik** [comment]
Sir,

0.21.1

**Comment by neuralpain** [comment]
I've reviewed the product numbers in the script and there does not seem to be any issue with them.

Did you have the activator running when you attempted to activate QuickBooks POS 19? If it's not running then the activation would fail.

**Comment by MalikandMalik** [comment]
Hello Sir,

Thank you for your reply.

Indeed, I throughly followed the steps using qb activator downloaded. I don’t know what’s going wrong with my system internally. 

Shouldn’t  I refresh my system windows and re-attempt then?

**Comment by neuralpain** [comment]
Before I send you to reinstall your OS, I want you to open the file explorer and jump to this location: `C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Intuit.Spc.Map.EntitlementClient.Common\v4.0_8.0.0.0__5dc4fe72edbcacf5`.

Let me know if you find a `.bak` file in the folder with the name `Intuit.Spc.Map.EntitlementClient.Common.dll.bak`. If you find this file, there should be a similar file without the extra `.bak` extension.

**Comment by MalikandMalik** [comment]
﻿Thanking you once again for your help.

I did the same as per your directives and find the following, also trying to attach the screen shot for your kind infos;




please advise for the next step to proceed with.

Thanking you,

**Comment by MalikandMalik** [comment]
Thanking you once again for your help.

I did the same as per your directives and find the following, also trying to attach the screen shot for your kind infos;






please advise for the next step to proceed with.

Thanking you,

**Comment by MalikandMalik** [comment]
﻿Hello Sir,

The attached picture with my earlier email seems like a blurry, however he is another one for your view.

**Comment by neuralpain** [comment]
I did not receive any images in your message. I would recommend that you comment directly on GitHub to upload the image

**Comment by MalikandMalik** [comment]
> I did not receive any images in your message. I would recommend that you comment directly on GitHub to upload the image

![image0](https://github.com/neuralpain/qbactivator/assets/159639036/b7fa56e4-075e-4e0d-9394-ca17bde5fe2b)

[Folder.pdf](https://github.com/neuralpain/qbactivator/files/14413330/Folder.pdf)

i tried to attach the folder information.

**Comment by neuralpain** [comment]
Alright. Most likely qbactivator was closed before it completed the activation.

1. Delete `"Intuit.Spc.Map.EntitlementClient.Common.dll"`
2. Remove the `".bak"` extension from `"Intuit.Spc.Map.EntitlementClient.Common.dll.bak"`
3. Run QuickBooks POS.

If that does not work then you would need to reinstall the QuickBooks POS application.
