### ISSUE TITLE
QB Desktop Point of Sale 19.0 Multistore Level Activation failed.

### ISSUE THREAD

**Issue by furu1985** [neuralpain/qbactivator#35]
QB Desktop Point of Sale 19.0 Multistore Level Activation failed.
When I enable multistore to add more stores, it is going to a trial mode, and requesting for New Product Number and Validation Code.

**Comment by furu1985** [comment]
Warning 176103
Quickbooks Desktop Point of Sale was unable to activate the product.

**Comment by neuralpain** [comment]
Did you run qbactivator before you attempted to add more users?

**Comment by shawn1361** [comment]
Possible to activate other QB products or just POS?

**Comment by neuralpain** [comment]
Currently only POS can be activated with qbactivator.

**Comment by bielo234** [comment]
quickbooks giving me invalid product number what should i do..

**Comment by neuralpain** [comment]
> quickbooks giving me invalid product number what should i do..

Use [this script](https://github.com/neuralpain/qbactivator/releases/tag/TemporaryInvalidProductCodeFix) to attempt to fix the product code issue. Run it then activate again with qbactivator.
