### ISSUE TITLE
i started qb activator 0.21 its starts but suddenly it closed what to do?

### ISSUE THREAD

**Issue by findupto** [neuralpain/qbactivator#36]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows edition: [e.g. 10, 11]
 - Version [e.g. 21H2, 22H2]
 - QuickBooks Product [e.g. POS v18, POS v19]

**Additional context**

**Comment by neuralpain** [comment]
Please check this section of the FAQs which might be similar to your issue. If you don't find a solution there, let me know.

https://github.com/neuralpain/qbactivator/wiki/FAQs#qbactivator-does-not-start--is-crashing

**Comment by neuralpain** [comment]
I also want to confirm: did you run qba v0.21.0 or v0.21.1?
