### ISSUE TITLE
Currency won't change from dollar to anyother, especially rupee.

### ISSUE THREAD

**Issue by ehtesham169** [neuralpain/qbactivator#41]
**Describe the bug**
I went to Youtube as well and got the guidance: that you have to change the region to India. But that didn't work at all. The software generates receipts with the currency being set to USD ($).

**Screenshots**

**Desktop (please complete the following information):**
 - Windows edition: 11
 - Version 23H2
 - QuickBooks Product [POS v19]

**Comment by itxshoaib** [comment]
i am also trying to find the solution. But there is not any option. Please comment if you find any tip.

**Comment by neuralpain** [comment]
Unfortunately, there isn't an option to turn on a multi-currency feature in QuickBooks Point of Sale.

**Comment by Mire990** [comment]
QB POS Does not support Multi Currency. but if you like to setup your Home currency symbol all you have to change is the settings from the Computer and set the default currency symbol from there and them QB POS should print what ever currency Symbol you specified from there.

**Comment by neuralpain** [comment]
> QB POS Does not support Multi Currency. but if you like to setup your Home currency symbol all you have to change is the settings from the Computer and set the default currency symbol from there and them QB POS should print what ever currency Symbol you specified from there.

Thanks @Mire990, this solution works well. However, if your currency symbol e.g. Rupee `₹`, Peso `₱` etc., is not supported in the software's character set, it gets replaces with a `?` placeholder, so you're basically out of luck.

I added a page to the Wiki which shows how to change the currency symbols on your PC as per @Mire990's comment: https://github.com/neuralpain/qbactivator/wiki/Changing-System-Currency-for-POS

**Comment by Mire990** [comment]
Oh! that is weird. so they should use something that is not symbol like INR or any Text.

**Comment by neuralpain** [comment]
Oh yeah, I forgot to mention that you can use text as well instead of a symbol. So @ehtesham169 can use `INR` instead of `₹` in the Windows settings to represent Rupee.

![Screenshot 2024-04-04 212255](https://github.com/neuralpain/qbactivator/assets/77242216/b5a6fb16-ca18-472a-8645-9e0873829371)
