### ISSUE TITLE
Windows Server 2012 - QBACTIVATOR NOT LOADING

### ISSUE THREAD

**Issue by iam-taijie** [neuralpain/qbactivator#44]
Hello Neural Pain,

I am trying to activate Quickbooks Point of Sale V11 (2013) on my Windows Server 2012 R2 Standard edition computer. However, when I try to run the qbactivator on my system, all it does, is show the cmd window and then displays some red words inside of the cmd window and then crashes.

Is there a way for me to run this activating tool on Windows Server 2012?

**Comment by neuralpain** [comment]
PowerShell version might be older than qbactivator supports. Update PowerShell with the latest version here: https://github.com/PowerShell/PowerShell/releases/latest

**Comment by clementkl** [comment]
hi Sir,
         Very appreciative of your work, thanks great job. Please is there any for accountants version?

**Comment by neuralpain** [comment]
> hi Sir, Very appreciative of your work, thanks great job. Please is there any for accountants version?

The only version I have right now with a working activation is Accountant 2013. The details are in the pinned in the TG group.

**Comment by clementkl** [comment]
ok so what's the name of the telegram group group please, if that's what you mean

**Comment by neuralpain** [comment]
https://t.me/qbactivator

**Comment by clementkl** [comment]
thanks but it says invalid incorrect product number. 462-240

**Comment by neuralpain** [comment]
> thanks but it says invalid incorrect product number. 462-240

The PN provided is 463-240. Review the license information and retry activation.

**Comment by clementkl** [comment]
thanks bro, but am currently restricted from posting in the telegram group, any reasons please? And please how do I get access to you directly

**Comment by neuralpain** [comment]
> thanks bro, but am currently restricted from posting in the telegram group, any reasons please? And please how do I get access to you directly

Restricted? That's strange. I haven't audited any user permissions for the group. You can [contact me here](https://t.me/neuralpain). There's also a link to my TG in my GitHub profile.

**Comment by clementkl** [comment]
![Screenshot_20240623-060633](https://github.com/neuralpain/qbactivator/assets/140783954/ab974765-0f01-4ce4-810e-14aa8f2e2490)
That's a screenshot of feedback I get when I try to contact you,

**Comment by clementkl** [comment]
![Screenshot_20240623-061341](https://github.com/neuralpain/qbactivator/assets/140783954/2fe53dc9-046e-41c2-b971-4b765a2ed3f7)
And this is when I try to post in the group

**Comment by neuralpain** [comment]
I checked again but it could be an issue with your account. Talk to [SpamBot](https://t.me/spambot) to see if you can get it resolved.

**Comment by Kaizen-4** [comment]
Hi Neuralpain, how do I resolve this issue? I already tried troubleshooting lv3 option in qbactivator-0.23.0 and got the same issue. 
![image](https://github.com/neuralpain/qbactivator/assets/173615592/c58d491b-7eca-4357-a3ae-0b4a3cf48456)

**Comment by neuralpain** [comment]
> Hi Neuralpain, how do I resolve this issue? I already tried troubleshooting lv3 option in qbactivator-0.23.0 and got the same issue.

This can happen if you have a QB Desktop product installed (Pro/Enterprise etc.). You need to first uninstall it and POS; install QuickBooks POS first, and then install the other QBDT products.
