### ISSUE TITLE
Pos Quikbooks 2019 error

### ISSUE THREAD

**Issue by Mikelab777** [neuralpain/qbactivator#47]
![20240622_083712](https://github.com/neuralpain/qbactivator/assets/173533216/21540069-ff7e-4f85-b095-9cb7de3f437b)
Please help
Keep getting We're sorry, QuikBooks Desktop point of sale has run into a problem, please restart
Running on Windows 11

**Comment by neuralpain** [comment]
> Please help Keep getting We're sorry, QuikBooks Desktop point of sale has run into a problem, please restart Running on Windows 11

1. Look for the folder C:\Program
1. Delete it
1. Restart QuickBooks

--
[(Dialog) QuickBooks Desktop Point of Sale has run into a prob...](https://github.com/neuralpain/qbactivator/wiki/FAQs#dialog-quickbooks-desktop-point-of-sale-has-run-into-a-problem-please-restart-the-program)
