### ISSUE TITLE
QB Pos activator

### ISSUE THREAD

**Issue by LexBizDir** [neuralpain/qbactivator#50]
Hi, the qbactivator (qbactivator-0.24.0) is crashing after a few seconds, i have gone through all the steps adding the lines in the system variables and checked  PShell v5.1 and updated C++ 

Edition	Windows 11 Home
Version	22H2
Installed on	‎09/‎02/‎2023
OS build	22621.2283
Serial number	MP1RM3Y9
Experience	Windows Feature Experience Pack 1000.22662.1000.0

Please help if you can

**Comment by neuralpain** [comment]
Be sure that you are not running qbactivator from within a ZIP file. Record a video of what happens when you run qbactivator and send it to me on Telegram.
