### ISSUE TITLE
INVALID PRODUCT NUMBER

### ISSUE THREAD

**Issue by MONKE121** [neuralpain/qbactivator#52]
At first I tried to install a client POS on my Laptop, my PC is the server which had a POS v19 when my laptop installed the client all icons colored grey for 10mins of waiting some icons turned colored but when I click it keeps saying " No support IU "Receipt" , or Cusomer .. 

Now I tried to uninstall and reinstall the POS on my PC Server, always INVALID PRODUCT NUMBER , I tried all version still the same I deleted all files location from 
• C:\Program Data\Intuit
• C:\Program Data\Common Files\Intuit
• C:\Users\[Username]\AppData\Local\Intuit
• C:\Program Files\Intuit
• C:\Program Files\Common Files\Intuit
• C:\Program Data\Intuit
• C:\Program Data\Common Files\Intuit
• C:\Users\\AppData\Local\Intuit
• C:\Program Files\Intuit
• C:\Program Files\Common Files\Intuit

![image](https://github.com/user-attachments/assets/30669a87-319b-45a2-9f83-09d726826e7e)

 and clean the registry using CCCleaner still all INVALID PRODUCT NUMBER
 
 Please help me I need the POS BADLY :(

**Comment by neuralpain** [comment]
Intuit was purged and a clean install of POS was done, followed by the other QBDT software.

**Comment by MONKE121** [comment]
BIG THANK HELP THANK YOU SO MUCH!
