### ISSUE TITLE
Unable to Install Quickbooks POS V19

### ISSUE THREAD

**Issue by bibleman19013** [neuralpain/qbactivator#53]
**Describe the bug**
I have been trying to install Quickbooks POS V19 since yesterday. The software extracts and then stops working with no error code. I was able ton install V11, V12, and V18 without issue.

**To Reproduce**
Attempt to install V19 on WIN11

**Expected behavior**
I expected the software to work perfectly. 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows edition: 11
 - Version Pro 22631
 - QuickBooks Product POS v19
 - qbactivator version qba-24

**Additional context**

**Comment by neuralpain** [comment]
Might be a driver issue. Try this [MS Visual C++ repack](https://github.com/abbodi1406/vcredist/releases/download/v0.83.0/VisualCppRedist_AIO_x86_x64.exe).

**Comment by bibleman19013** [comment]
Good morning. I tried the repack but it was unsuccessful: however, I
reinstalled the Windows and it successfully installed. Thank you for your
assistance.

**Comment by dkcomputer2121** [comment]
please give me 
licence number and product number

**Comment by bibleman19013** [comment]
The issue has been resolved. Thank you.
