### ISSUE TITLE
Quickbooks could not activate

### ISSUE THREAD

**Issue by Vergino7** [neuralpain/qbactivator#8]
I did everything properly, from step one to the last step. But when I insert the activation code it gives the error on d picture below. 
![20230123_194321](https://user-images.githubusercontent.com/123408545/214134674-c05c53ef-7679-4a81-8411-e806a5e6dcbd.jpg)

**Comment by Vergino7** [comment]
@neuralpain

**Comment by neuralpain** [comment]
> But when I insert the activation code it gives the error on d picture below.

It seems that you tried to enter the registration code on the first popup of the "registration window". In that case you will get an error because the patch has not taken effect as the UI isn't ready.

You should only attempt to enter the registration code **after** you successfully enter practice mode with the sample data and select "Registration" through the "Help" menu.

Reinstall QB software and attempt to activate it again. Follow steps 10-17 carefully.

Let me know if this helps.

— NP

**Comment by Vergino7** [comment]
I did everything properly. But I am going to try it again step by step. I wish we could do a video call so u see it as I do it.

**Comment by Vergino7** [comment]
Tried it again. Still same error. Will show you the picture below. ![20230124_080634.jpg](https://user-images.githubusercontent.com/123408545/214231517-2b99555d-836a-438c-a351-c96787e7d33d.jpg)

@neuralpain

**Comment by Vergino7** [comment]
@neuralpain still waiting for a response

**Comment by neuralpain** [comment]
> I did everything properly. But I am going to try it again step by step. I wish we could do a video call so u see it as I do it.

Message me on Telegram: https://t.me/neuralpain
I may not be able to respond immediately but I will assist you further there.

**Comment by Vergino7** [comment]
Ok

**Comment by Vergino7** [comment]
It said I can't send u a message on telegram. Cos we are not mutual contacts

**Comment by Vergino7** [comment]
@neuralpain

**Comment by neuralpain** [comment]
After QuickBooks was installed, did you press a key to continue the activator as shown in the image below?

![qbactivator-main-screen](https://user-images.githubusercontent.com/77242216/214317493-e208d7f0-fc76-4142-a0b9-08da7f3d73c7.png)

I was able to recreate the error when I tried to activate without allowing the script to continue.

The activation cannot begin without a QuickBooks installation. This is why the script is paused during the installation of the POS software. After the installation, you need to continue the script so it can enable the services for successful activation.

Let me know if this helped.

**Comment by Vergino7** [comment]
The script continued o.
I am starting afresh again on another system. I will surely get back to you.

**Comment by Vergino7** [comment]
Still the same error on d fresh system ![20230124_154533.jpg](https://user-images.githubusercontent.com/123408545/214325267-6bad1b35-e687-4712-9f09-39be835762b3.jpg)

**Comment by neuralpain** [comment]
I see that you are offline (taskbar). QuickBooks needs to connect to the internet for activation. Check your connection and try again.

**Comment by Vergino7** [comment]
Finally it worked, thanks to @neuralpain for the help he gave to me. I will post a video of proof. I installed It on 3 systems ![20230124_171556.jpg](https://user-images.githubusercontent.com/123408545/214374374-3182fa67-6a78-4fda-8acd-7131536c8d3f.jpg)

**Comment by Vergino7** [comment]
![Screenshot_20230124_192054_Gallery.jpg](https://user-images.githubusercontent.com/123408545/214375852-3127686d-e448-42fa-9463-1d5e78b1dd75.jpg)

![Screenshot_20230124_192045_Gallery.jpg](https://user-images.githubusercontent.com/123408545/214375850-abdc003e-afbd-4c5b-90ac-41f333667812.jpg)

![Screenshot_20230124_192038_Gallery.jpg](https://user-images.githubusercontent.com/123408545/214375851-f4c9fdee-a751-433f-9ccf-59517889e2ea.jpg)




Three different systems.
